version: "3"
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    build: ./postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: vectordb

  conversation_service:
    build: ./conversation_service
    ports:
      - "5000:80"
    depends_on:
      - postgres

  ai_service:
    build: ./ai_service
    ports:
      - "8000:80"
    env_file:
      - .env
    depends_on:
      - postgres

  frontend_italian:
    build: ./frontend_italian
    ports:
      - "3000:3000"

  frontend_korean:
    build: ./frontend_korean
    ports:
      - "4000:4000"

volumes:
  redis_data:
  redis2_data:
